spring:
  application:
    name: rating-service
  config:
    import: optional:configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: hotels

server:
  port: 8083